apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: n
  name: n
spec:
  replicas: 1
  selector:
    matchLabels:
      app: n
  template:
    metadata:
      labels:
        app: n
    spec:
      containers:
      - image: nginx
        name: nginx
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: n
  name: nginx
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: n
  type: LoadBalancer